### ISSUE TITLE
[Bug] Inputting / changing birthday on Actor detail page doesn't work.

### ISSUE THREAD

**Issue by sjclayton** [curtwagner1984/YAPO#19]
Attempting to input or change a birthday on an Actor detail page doesn't work either by manually entering the date, or by trying to use the calendar button.

**Comment by curtwagner1984** [comment]
Should work now.

**Comment by sjclayton** [comment]
The date picker appears now, but if you put in a new date it doesn't get saved...

Also it seems to be taking any dates that are already in the database and offsetting them by one day earlier... like if an actresses b-day is November 22 it'll change it to the 21st in the display window.

**Comment by curtwagner1984** [comment]
That's weird ... It saves it on my end ... Do you get a 200 code for the put request ? 
You can also see the return codes from the inspect tools in chrome under network.

**Comment by sjclayton** [comment]
`[26/Aug/2016 17:48:20] "PUT /api/actor/1/ HTTP/1.1" 200 925
` is what I get... so yes, I get a 200.... but it still does not save..

There is also the issue of the offset that is happening that I mentioned above ^^.

**Comment by curtwagner1984** [comment]
It's strange on my end, there is no offset of the date.
![chrome_2016-08-27_15-40-41](https://cloud.githubusercontent.com/assets/20076369/18027475/e9cafb3e-6c6c-11e6-9114-74bbc14ed6be.jpg)

This is the line that takes the date from the db and puts it on the interface variable:
```javascript
self.birthdate = new Date(res.date_of_birth);
```
(In actor-detail.component.js)

Then on date change this function translates the js date into a format that django is comfortable with :
```javascript
self.updateBirthday = function (actor) {

                var dd = self.birthdate.getDate();
                var mm = self.birthdate.getMonth() + 1; //January is 0!
                var yyyy = self.birthdate.getFullYear();


                actor.date_of_birth = yyyy + '-' + mm + '-' + dd;

                self.updateActor(actor);

            };
```
There is nothing here that supposed to offset the day by 1.

Try comparing the date that it displays with the date in the api (replace #! with api so http://127.0.0.1:8000/#!/actor/114 is http://127.0.0.1:8000/api/actor/114) and see if the offset is there too.

**Comment by sjclayton** [comment]
I checked the REST API before and the birth date is correct in there (no offset)...

So I dunno *shrugs*.... this is very weird...

**Comment by curtwagner1984** [comment]
Perhaps it's a linux thing... Maybe the date format is a bit different.
Can you try to zero in on the problem? At some point after it gets the info from the server it changes the value for the DOB. 
You can debug with chrome devtools, it's built in chrome and has breakpoints and watches.
You can start by setting a breakpoint on line 137 in actor-detail.component.js `self.birthdate = new Date(res.date_of_birth);' this is where the page gets the birthdate from the server. You can try and print it out after this point to see if it's correct there using:
```javascript
alert(self.birthdate);
```

This is also the only line that is responsible for what date is shown after loading. Other lines that has to do with self.birthdate are called only if there is a change to the date.

**Comment by sjclayton** [comment]
@curtwagner1984 Setting a breakpoint on line 137 and calling `alert(self.birthdate);` returns: `null`

**Comment by curtwagner1984** [comment]
Apparently it's because of the GMT. In the database it's 29 oct 1990 and the time defaults to 00:00 so it's `Mon Oct 29 1990 00:00:00 GMT 0000` because your GMT is -5 it subtracts 5 hours from this date so you get `Sun Oct 28 1990 19:00:00 GMT-0500 (EST)`

One of the suggestions on the angular ui page was this 
```javascript
var d = new Date('yourDate');
d.setMinutes( d.getMinutes() + d.getTimezoneOffset() );

// 'd' should be the correct date
```
Try this and see if it helps (line 137):
```javascript
var d = new Date(res.date_of_birth);
d.setMinutes( d.getMinutes() + d.getTimezoneOffset() );
self.birthdate = d;
```
This should take the wrong date and add the timezoneoffset back to it.

**Comment by sjclayton** [comment]
@curtwagner1984 That worked!!

**Comment by curtwagner1984** [comment]
I've merged your pull request. This should work correctly for everyone now.

**Comment by cooperdk** [comment]
There is an error in the page controller which breaks updating the birthdate. It is fixed in my fork.
[https://github.com/cooperdk/YAPO-e-plus](YAPO e+)
